const STORE = {
    //question/answer information
    //correct answer
    {},{},{},{}
}

let questionCounter = 0

function startQuiz {
    //event listener for start button on HTML
    //iterate through STORE and present first question
    //create a separate function to iterate through STORE
}

function onQuestion{
    //start on questionCounter
    //grab the object within the array and render for user
    //remove current HTML within "quizArea" and add STORE[questionCounter]

}

function submitAnswer{
    //event listener for the Submit button that is generated by onQuestion
    //compare USER answer to correct answer
    
}

function feedbackContinue{
    //create Continue button, add event listener to it
    //if correct --> popup answer correct
    //if incorrect --> popup sorry, but x was the correct answer
    //When click on Continue, close popup, questionCounter +=, 
    //run onQuestion to render for user 
}

function quizRestart{
    //event listener at the end
    //present score, give feedback
    //Restart button
}

